name: Gradle Precommit
on: [push,pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt
      - name: Config JDK8 env
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo ::set-env name=JAVA8_HOME::$(echo $JAVA_HOME)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Config JDK17 env
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo ::set-env name=JAVA17_HOME::$(echo $JAVA_HOME)

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle
        run: |
          ./gradlew precommit --parallel
